### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [tonyg/erlang-nacl#5]
Hi @tonyg, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by tonyg** [comment]
Hi Sam, thanks for writing: no, I haven't touched this library in a long time, and I do now know if it works or even builds against current Erlang. A quick google suggests there are a few other bindings out there for Erlang, so I think little would be lost if you dropped this one from the index.
